### ISSUE TITLE
1.7

### ISSUE THREAD

**Issue by the-reverend** [wlbr/csvfix#1]
i have a zip copy of csvfix 1.7 : neilb-csvfix-93804d497be6.zip. let me know if you want to check it out. might be some worthwhile improvements in here. it builds in WSL last time i checked in 2018.

**Comment by the-reverend** [comment]
```
[...]/src/neilb-csvfix-93804d497be6/csvfix/bin$ ./csvfix

CSVfix 1.7 (Dec  5 2018)
Copyright (C) 2014 Neil Butterworth
This is free software; see the source for copying conditions. There is NO
warranty, not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configuration file: none

csvfix is a CSV stream editor
use 'csvfix help' to see a list of commands
use 'csvfix help command' to see help on a specific command
```

**Comment by wlbr** [comment]
Hey, it would be nice if you could share the copy, though I cannot promise that I find the time to include it soon.

**Comment by the-reverend** [comment]
i put it on my dropbox ~here~; let me know once you grab it and i'll take it down.

**Comment by the-reverend** [comment]
also, someone forked your repo and fixed a bug, calling it 1.6.1 ... hehe. might be worth a PR?

**Comment by wlbr** [comment]
Thanks, got it. 
Hope I will find the time.

Regards,
Michael

**Comment by the-reverend** [comment]
yw!
